### PR TITLE
Allows strings as a partial name

### PR DESCRIPTION
**Pull request by jcreamer898**
Allows partial's to contain a string rather than just only an identifier...

```html
{{> "path/to/partial"}}
```

### CODE REVIEW

**Comment by nowhereman** [comment]
:+1:

**Comment by jamesotron** [comment]
Thanks!

**Comment by jcreamer898** [comment]
No problem!

**Comment by jcreamer898** [comment]
@jamesotron is there anything I can help with to get this change to be up in the ruby gem repo? Seems to not reflect the change still. Thanks!

**Comment by jamesotron** [comment]
Oh, I probably haven't done a release. Let me check...

**Comment by jamesotron** [comment]
Version `0.3.5` tagged and pushed to Rubygems.

**Pull request merged**
