### PR TITLE
adds subexpression support

### PR DESCRIPTION
**Pull request by meesterdude**
This PR adds support for subexpressions. Works for simple helpers, block helpers, nested, and as hash parameters. 

```
{{sum 1 (sum 1 (sum 1 1))}}
#=> 4
```

Let me know if there's anything this needs to go out the door!

also snuck in some docs for raw blocks, added previously

### CODE REVIEW

**Comment by jamesotron** [comment]
Wow. This is a lot of work!

**Comment by meesterdude** [comment]
@jamesotron iroinically, took me maybe 20 minutes to get the code working. the last feature i submitted took several days.

**Comment by meesterdude** [comment]
(also, specs pass locally, not sure whats up with CI)

**Comment by jamesotron** [comment]
Thanks!

**Pull request merged**
